### ISSUE TITLE
Propogate Corner components to other masters

### ISSUE THREAD

**Issue by elenage** [mekkablue/Glyphs-Scripts#122]
The script doesn't seem to work
Glyphs - Version 2.4.2 (1017)
Here is the error text:
"Start
Processing B
Traceback (most recent call last):
  File "Propagate Corner Components to Other Masters.py", line 56, in <module>
    process( thisLayer )
  File "Propagate Corner Components to Other Masters.py", line 37, in process
    name = h.name()
TypeError: 'objc.pyobjc_unicode' object is not callable
End
"

**Comment by mekkablue** [comment]
I think I fixed it.

**Comment by elenage** [comment]
Thank you! I think it works :)
