### ISSUE TITLE
Components: Diacritic Ligature Maker

### ISSUE THREAD

**Issue by elenage** [mekkablue/Glyphs-Scripts#126]
This one doesn't seem to work.
Here is the error text:
```
Creating variations for K_A:
Traceback (most recent call last):
  File "Diacritic Ligature Maker.py", line 100, in <module>
    listOfLigatures = process( thisGlyphName )
  File "Diacritic Ligature Maker.py", line 75, in process
    diacriticLetterLists = [ [n]+namesOfGlyphsContainingThisComponent(n) for n in namesOfLigatureLetters ]
  File "Diacritic Ligature Maker.py", line 32, in namesOfGlyphsContainingThisComponent
    listOfGlyphs = selectTool._glyphsContainingComponentWithName_font_masterID_( componentName, thisFont, thisFontMasterID )
AttributeError: 'GSToolSelect' object has no attribute '_glyphsContainingComponentWithName_font_masterID_'
End
```

**Comment by mekkablue** [comment]
Just uploaded a fix.

**Comment by elenage** [comment]
thank you!
