### ISSUE TITLE
Insert Instances error on 10.9.5

### ISSUE THREAD

**Issue by KseniaKarataeva** [mekkablue/Glyphs-Scripts#154]
When you run insert instances on 10.9.5, you get this error:

```
Traceback (most recent call last):
  File "Insert instances.py", line 389, in <module>
    InstanceMaker()
  File "Insert instances.py", line 123, in __init__
    self.w.firstName.enable( self.w.naturalNames.isEnabled() )
AttributeError: 'CheckBox' object has no attribute 'isEnabled'

```

**Comment by KseniaKarataeva** [comment]
Sorry, not working still:

```python
Traceback (most recent call last):
  File "Insert instances.py", line 392, in <module>
    InstanceMaker()
  File "Insert instances.py", line 123, in __init__
    self.w.firstName.enable( self.w.naturalNames.getNSButton().isEnabled() )
  File "/Users/Ksenia/Library/Application Support/Glyphs/Scripts/vanilla/vanillaCheckBox.py", line 194, in getNSButton
    raise NotImplementedError
NotImplementedError
```

**Comment by mekkablue** [comment]
I think I fixed it now.
