### ISSUE TITLE
Sync components across all masters broken - Glyphs 3, Big Sur

### ISSUE THREAD

**Issue by albertomalossi** [mekkablue/Glyphs-Scripts#207]
Per title. Log:

Traceback (most recent call last):
  File "Sync Components Across Masters.py", line 50
    raise e
  File "Sync Components Across Masters.py", line 42
    process( thisLayer )
  File "Sync Components Across Masters.py", line 27, in process
    thatLayer.components = newComponents
AttributeError: can't set attribute

**Comment by albertomalossi** [comment]
Still broken after update:

Traceback (most recent call last):
  File "Sync Components Across Masters.py", line 69
    raise e
  File "Sync Components Across Masters.py", line 61
    process( thisLayer )
  File "Sync Components Across Masters.py", line 46, in process
    thatLayer.components = newComponents
AttributeError: can't set attribute

**Comment by mekkablue** [comment]
Thanks for reporting.
