### ISSUE TITLE
Insert Instances Script in G3 issue

### ISSUE THREAD

**Issue by ammazzarella** [mekkablue/Glyphs-Scripts#210]
Insert Instances script doesn't work in a file with four masters (two for width, two for weight). Clicking on Insert button give this result in macro panel and no instance is created:

```
__typ <objective-c class GSInstance at 0x1020b4ee0>
Traceback (most recent call last):
  File "Insert Instances.py", line 506, in CreateInstances
  File "Insert Instances.py", line 215, in widthID
AttributeError: 'InstanceMaker' object has no attribute 'axisId'

'GSInstance' object has no attribute 'weightValue'
Traceback (most recent call last):
  File "Insert Instances.py", line 506, in CreateInstances
  File "Insert Instances.py", line 215, in widthID
AttributeError: 'InstanceMaker' object has no attribute 'axisId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Insert Instances.py", line 515, in CreateInstances
AttributeError: 'GSInstance' object has no attribute 'weightValue'

```

The script works fine on the same file in G2 or in a two masters file (I have tried weight) in G3

**Comment by mekkablue** [comment]
Should be fixed by now. Can you confirm?

**Comment by ammazzarella** [comment]
Yes it is! Thank you.
