### ISSUE TITLE
Insert Instances in Glyphs 2

### ISSUE THREAD

**Issue by mekkablue** [mekkablue/Glyphs-Scripts#216]
Running _Interpolation > Insert Instances_ throws a lot of errors in Macro Window before the window appears:

```python
Start
Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 225, in MasterList
    weightAxisID = self.weightID(thisFont)
  File "Insert Instances.py", line 204, in weightID
    weightAxisID = self.axisID(weightAxis)
  File "Insert Instances.py", line 198, in axisID
    return axis.axisId
AttributeError: '__NSDictionaryI' object has no attribute 'axisId'

Traceback (most recent call last):
  File "Insert Instances.py", line 370, in LoadPreferences
    self.w.numberOfInstances.set( Glyphs.defaults["com.mekkablue.InstanceMaker.numberOfInstances"] )
  File "vanillaPopUpButton.py", line 98, in set
    self._nsObject.selectItemAtIndex_(value)
ValueError: depythonifying 'long long', got 'objc.pyobjc_unicode' of 1
```

**Comment by mekkablue** [comment]
I assume the try/except clauses need to be replaced with a better check for `Glyphs.appVersion>=3`.
