### ISSUE TITLE
Build Symbols scripts buggy: "unexpected keyword argument" error

### ISSUE THREAD

**Issue by mekkablue** [mekkablue/Glyphs-Scripts#231]
```python
🔣 Building estimated:
Build Symbols Error: createGlyph() got an unexpected keyword argument 'override'
Traceback (most recent call last):
  File "Build Symbols.py", line 619, in BuildSymbolsMain
    buildEstimated(thisFont, override=override)
  File "Build Symbols.py", line 270, in buildEstimated
    estimatedGlyph = createGlyph(thisFont, glyphname, "212E", override=override)
TypeError: createGlyph() got an unexpected keyword argument 'override'
```

**Comment by RafalBuchner** [comment]
have you worked on that? script looks like a working one

**Comment by mekkablue** [comment]
Cannot reproduce anymore, you are right.
