### ISSUE TITLE
Circled digits not working

### ISSUE THREAD

**Issue by irispils** [mekkablue/Glyphs-Scripts#246]
Here's the log:

```
⚠️ Script Error:

Traceback (most recent call last):
  File "Build Circled Glyphs.py", line 708, in BuildCircledGlyphsMain
    radius = circleGlyph.layers[thisMaster.id].paths[1].bounds.size.width * 0.5
  File "GlyphsApp/GlyphsApp/__init__.py", line 460, in GSProxyShapes__getitem__
IndexError: list index out of range


Build Circled Glyphs Error: list index out of range
Traceback (most recent call last):
  File "Build Circled Glyphs.py", line 798, in BuildCircledGlyphsMain
    raise e
  File "Build Circled Glyphs.py", line 708, in BuildCircledGlyphsMain
    radius = circleGlyph.layers[thisMaster.id].paths[1].bounds.size.width * 0.5
  File "GlyphsApp/GlyphsApp/__init__.py", line 460, in GSProxyShapes__getitem__
IndexError: list index out of range
```

**Comment by ampersandio** [comment]
Get the same error with Glyphs3

**Comment by schriftgestalt** [comment]
It seems that the script expects that the circleGlyph contains two paths.

**Comment by ampersandio** [comment]
OK, this worked! Thanks
