### ISSUE TITLE
'Glyphs' is not defined

### ISSUE THREAD

**Issue by wenzeldaniel** [mekkablue/Glyphs-Scripts#271]
Apple M1 Max, macOS Monterey 12.3.1

```
Traceback (most recent call last):

  File "…/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBase.py", line 505, in action_
    self.callback(sender)

  File "…/Library/Application Support/Glyphs/Scripts/mekkablue/Kerning/Adjust Kerning in Master.py", line 211, in AdjustKerningMain
    raise e

NameError: global name 'Glyphs' is not defined

```

**Comment by wenzeldaniel** [comment]
also in Macro Pannel:

```
Traceback (most recent call last):
  File "<macro>", line 2, in <module>
  File "_lazyimport.py", line 154, in __getattr__
    raise AttributeError(name)
AttributeError: Swift.__RawSetStorage
Start
Note: 'Adjust Kerning in Master' could not load preferences. Will resort to defaults
End
```

**Comment by schriftgestalt** [comment]
Is this Glyphs 2? Then you need to install pyobjc: https://glyphsapp.com/news/glyphs-2-on-monterey
