### ISSUE TITLE
Center Glyphs fails

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#287]
```

⚠️ 'Center Glyphs' Script Error:

Traceback (most recent call last):
  File "Center Glyphs.py", line 37
    thisLayer.applyTransform(shift)
  File "GlyphsApp/GlyphsApp/__init__.py", line 8800, in __GSLayer_applyTransform__
NameError: name 'NSAffineTransformStruct' is not defined


Traceback (most recent call last):
  File "Center Glyphs.py", line 45
    raise e
  File "Center Glyphs.py", line 37
    thisLayer.applyTransform(shift)
  File "GlyphsApp/GlyphsApp/__init__.py", line 8800, in __GSLayer_applyTransform__
NameError: name 'NSAffineTransformStruct' is not defined

```

**Comment by schriftgestalt** [comment]
That is my fault. Will need to update Glyphs.

**Comment by weiweihuanghuang** [comment]
I made a simpler version of this script:

```
def process( thisLayer ):
	LSB = thisLayer.LSB
	RSB = thisLayer.RSB
	width = thisLayer.width

	halfSB = (LSB + RSB)/2
	thisLayer.LSB = int(halfSB)
	thisLayer.RSB = int(halfSB)
	thisLayer.width = width

thisFont.disableUpdateInterface() # suppresses UI updates in Font View

for thisLayer in listOfSelectedLayers:
	thisGlyph = thisLayer.parent
	numberOfLayers = len( thisGlyph.layers )
	for i in range( numberOfLayers )[::-1]:
		thisOtherLayer = thisGlyph.layers[i]
		print "Processing", thisGlyph.name
		thisGlyph.beginUndo() # begin undo grouping
		process( thisOtherLayer )
		thisGlyph.endUndo()   # end undo grouping

thisFont.enableUpdateInterface() # re-enables UI updates in Font View
```
