### ISSUE TITLE
Brace and Bracket Manager crash

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#305]
Trying to re-map selected glyphs, then get:
```
Brace and Bracket Manager Report for Playfair
/Users/claus/Git/clauseggers/Playfair/sources/Playfair-2_1-Roman.glyphs

🔢 Attempting Optical size: 75 → 95
Brace and Bracket Manager Error: 'a01'
Traceback (most recent call last):
  File "Brace Layer Manager.py", line 235, in BraceLayerManagerMain
    axisLimits = axisRules[axisID]
  File "_convenience_mapping.py", line 18, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "_convenience.py", line 113, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'a01'
```

Before this, I changed my masters from widths 75 and 150 to 95 and 114.

**Comment by clauseggers** [comment]
I can see that selecting fewer glyphs to run this on will work.

**Comment by mekkablue** [comment]
It chokes on (the first master of) a specific glyph. I’ll add a report line, so you can track down in which glyph it is happening.
