### ISSUE TITLE
Propagate Corner Components to Other Masters borks

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#311]
```
Processing E

⚠️ Script Error:

Traceback (most recent call last):
  File "Propagate Corner Components to Other Masters.py", line 65
    process(thisLayer)
  File "Propagate Corner Components to Other Masters.py", line 47, in process
    nodeIndex = indexOfNode(thisLayer, pathIndex, h.originNode)
  File "Propagate Corner Components to Other Masters.py", line 19, in indexOfNode
    for i in range(len(l.paths[pi].nodes)):
  File "GlyphsApp/GlyphsApp/__init__.py", line 579, in __GSProxyShapes__getitem__
TypeError: '<' not supported between instances of 'NoneType' and 'int'


Traceback (most recent call last):
  File "Propagate Corner Components to Other Masters.py", line 74
    raise e
  File "Propagate Corner Components to Other Masters.py", line 65
    process(thisLayer)
  File "Propagate Corner Components to Other Masters.py", line 47, in process
    nodeIndex = indexOfNode(thisLayer, pathIndex, h.originNode)
  File "Propagate Corner Components to Other Masters.py", line 19, in indexOfNode
    for i in range(len(l.paths[pi].nodes)):
  File "GlyphsApp/GlyphsApp/__init__.py", line 579, in __GSProxyShapes__getitem__
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by mekkablue** [comment]
Cannot reproduce. Can you send me the E that triggered it?

**Comment by clauseggers** [comment]
I’ll send you the whole file.
