### ISSUE TITLE
Error when running Bracket & Brace Manager

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#318]
```
Brace and Bracket Manager Report for Playfair
/Users/claus/Git/clauseggers/Playfair/sources/Playfair-2_2-Roman.glyphs

🔢 Attempting Optical size: 800.0 → 400.0
{
    a01 =     {
        max = 800;
    };
}
Brace and Bracket Manager Error: '__NSSingleEntryDictionaryI' object does not support item assignment
Traceback (most recent call last):
  File "Brace Layer Manager.py", line 251, in BraceLayerManagerMain
    axisLimits[border] = replaceWith
    ~~~~~~~~~~^^^^^^^^
TypeError: '__NSSingleEntryDictionaryI' object does not support item assignment
```

**Comment by schriftgestalt** [comment]
Can you reproduce that?

**Comment by clauseggers** [comment]
Yes. Open one of the Playfair files I sent to you today, select all the glyphs and then run it like this
<img width="396" alt="Screenshot 2024-01-10 at 17 41 57" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/e8def615-1749-4b40-8701-843b67a64fa5">

I then get the same issue:
```
Brace and Bracket Manager Report for Playfair
/Users/claus/Git/clauseggers/Playfair/sources/Playfair-2_2-Roman.glyphs

🔢 Attempting Optical size: 800.0 → 400.0
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 400;
    };
    a02 =     {
        max = 97;
    };
    a03 =     {
        min = 700;
    };
}
{
    a01 =     {
        max = 800;
    };
}
Brace and Bracket Manager Error: '__NSSingleEntryDictionaryI' object does not support item assignment
Traceback (most recent call last):
  File "Brace Layer Manager.py", line 251, in BraceLayerManagerMain
    axisLimits[border] = replaceWith
    ~~~~~~~~~~^^^^^^^^
TypeError: '__NSSingleEntryDictionaryI' object does not support item assignment


```

**Comment by clauseggers** [comment]
If you just want one glyph, I found one: use `_f_j.ligature`
