### ISSUE TITLE
Find and Replace components script not working

### ISSUE THREAD

**Issue by RosaWagner** [mekkablue/Glyphs-Scripts#321]
Script was working recently, but not with update 3.2 (3234)
Macro panel only report this: 

```
Find and Replace Components, report for Fontname
/path/to/sources.glyphs
```

**Comment by SophiaDesign** [comment]
I'm having the same issue – updated to 3.2 (3241) and still doesn't work except "0 changes" message does not appear in a message box. It appears in the macro panel instead.

Macro panel:
```
Traceback (most recent call last):
  File "__init__.py", line 152, in SavePreferences
    Glyphs.defaults[self.domain(prefName)] = self.uiElement(prefName).get()
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 131, in uiElement
    latestObject = getattr(latestObject, particle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FloatingWindow' object has no attribute 'oldCompName'

⚠️ ‘ComponentReplacer’ could not write preferences.
Find and Replace Components, report for Fontname 
/path/sources/fontname.glyphs

	✅ Replaced 0 components in ibreve.sc, layer: Regular

Done. Replaced 0 components.
```

**Comment by schriftgestalt** [comment]
That is fixed already. Please make sure you have the latest version. e.g. by removing and re-installing the mekkablue scripts in Plugin Manager.
