### ISSUE TITLE
Anchor Mover

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#323]
```
Traceback (most recent call last):
  File "Anchor Mover.py", line 267
    AnchorMover2()
  File "Anchor Mover.py", line 108, in __init__
    self.w = vanilla.FloatingWindow((500, 175), "Anchor Mover", minSize=(370, 175), maxSize=(1000, 175), autosaveName=self.pref("mainwindow"))
                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 109, in pref
    return self.prefDict[prefName]
           ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'mainwindow'
```

**Comment by schriftgestalt** [comment]
fixed it.
