### ISSUE TITLE
Find and Replace Components no longer working

### ISSUE THREAD

**Issue by naipefoundry** [mekkablue/Glyphs-Scripts#329]
I'm on a M2 Mac with MacOS Sonoma 14.3.1 (23D60) and Glyphs 3.2 (3243). 

The Find and Replace Components now throws this error: 

```
Traceback (most recent call last):
  File "__init__.py", line 152, in SavePreferences
    Glyphs.defaults[self.domain(prefName)] = self.uiElement(prefName).get()
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 131, in uiElement
    latestObject = getattr(latestObject, particle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FloatingWindow' object has no attribute 'oldCompName'

⚠️ ‘ComponentReplacer’ could not write preferences.
```

**Comment by schriftgestalt** [comment]
That should be fixed already. Can you remove and re-install the mekkablue script from the Plugin Manager.
