### ISSUE TITLE
Issue with Batch Add Smart Axes

### ISSUE THREAD

**Issue by naipefoundry** [mekkablue/Glyphs-Scripts#338]
Batch Add Smart Axes is not running for me.

I'm in Glyphs 3301 running python version 3.11.6 (Glyphs) using a M2 Mac Studion with Sonoma 14.4.1

Here's the macro panel error:

```
Traceback (most recent call last):
  File "Batch-Add Smart Axes.py", line 188
    BatchAddSmartAxes()
  File "Batch-Add Smart Axes.py", line 51, in __init__
    legibleFont = getLegibleFont()
                  ^^^^^^^^^^^^^^^^
  File "__init__.py", line 111, in getLegibleFont
    size = NSFont.systemFontSize()
           ^^^^^^
NameError: name 'NSFont' is not defined
```

**Comment by naipefoundry** [comment]
Same for "Make Components Smart in All Selected Glyphs"

```
Traceback (most recent call last):
  File "Make Components Smart.py", line 13
    fontAxisValues = [m.axes[i] for m in font.masters]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Make Components Smart.py", line 13, in <listcomp>
    fontAxisValues = [m.axes[i] for m in font.masters]
                             ^
NameError: name 'i' is not defined. Did you mean: 'id'?

```
