### ISSUE TITLE
Rebuild Components error

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#39]
```
Start
Rebuilding Ccaron
Traceback (most recent call last):
  File "Rebuild Components.py", line 80, in <module>
    process( thisLayer )
  File "Rebuild Components.py", line 53, in process
    accentLayer = accent.layers[ FontMaster.id ]
AttributeError: 'NoneType' object has no attribute 'layers'
End
```

Glyphs 2 (699)

**Comment by weiweihuanghuang** [comment]
I'm finding that it only works for some glyphs? Why is that?

**Comment by mekkablue** [comment]
Merged your pull. Thank you.
