### ISSUE TITLE
Diacritic Ligature Maker Error

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#48]
```
Traceback (most recent call last):
  File "Diacritic Ligature Maker.py", line 92, in <module>
    allNewLigatures += process( thisGlyphName )
  File "Diacritic Ligature Maker.py", line 72, in process
    diacriticLetterLists = [ [n]+namesOfGlyphsContainingThisComponent(n) for n in namesOfLigatureLetters ]
  File "Diacritic Ligature Maker.py", line 33, in namesOfGlyphsContainingThisComponent
    listOfGlyphs = selectTool._glyphsContainingComponentWithName_font_masterID_( componentName, thisFont, thisMaster.id )
NameError: global name 'thisMaster' is not defined
```

**Comment by mekkablue** [comment]
Fixed. Thx for reporting.
