### ISSUE TITLE
Diacritic Ligature Maker Error

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#49]
```
    Creating n_eogonek
Traceback (most recent call last):
  File "Diacritic Ligature Maker.py", line 92, in <module>
    allNewLigatures += process( thisGlyphName )
  File "Diacritic Ligature Maker.py", line 77, in process
    createLigatureWithBaseLigature( diacriticLigatureName, thisLigatureName )
  File "Diacritic Ligature Maker.py", line 63, in createLigatureWithBaseLigature
    anchorBaseName = [ a.name[1:] for a in thisComponent.component.layers[thisFontMasterID].anchors if a.name in baseGlyphAnchorNameLists[i] ][0]
IndexError: list index out of range
```

**Comment by mekkablue** [comment]
Looks like the ligature did not have all required anchors on all masters. I uploaded a new version that does better error reporting.
