### ISSUE TITLE
All Anchors in All Layers.py not working with 0 width glyphs

### ISSUE THREAD

**Issue by zar-nicolas20** [mekkablue/Glyphs-Scripts#62]
I am working in a Arabic font (in Glyphs Version 2.1 [766]), and I just insert a new Master and I am trying to place all the anchors in all the masters. The feature is printing how is working but it is stopped in the first 0 width glyphs.
Output panel warns the following.
```
Traceback (most recent call last):
  File "All Anchors in All Layers.py", line 66, in <module>
    print process( thisGlyph )
  File "All Anchors in All Layers.py", line 34, in process
    allAnchorDict = allAnchorsOfThisGlyph( thisGlyph )
  File "All Anchors in All Layers.py", line 19, in allAnchorsOfThisGlyph
    thisAnchorInfo = ( thisAnchor.x / thisWidth, thisAnchor.y )
ZeroDivisionError: float division by zero
```

**Comment by mekkablue** [comment]
Fixed it.
