### ISSUE TITLE
Report Area in Square Units error

### ISSUE THREAD

**Issue by dadastudio** [mekkablue/Glyphs-Scripts#64]
Hi,

I got this error when running the script:

Area of o:
Traceback (most recent call last):
  File "Report Area in Square Units.py", line 70, in <module>
    process( thisLayer )
  File "Report Area in Square Units.py", line 59, in process
    area = areaForLayer( thisLayer, PRECISION )
  File "Report Area in Square Units.py", line 55, in areaForLayer
    area += sizeOfSlice( cleanLayer, measurementHeight )
  File "Report Area in Square Units.py", line 33, in sizeOfSlice
    listOfIntersections = sliceIntersections( thisLayer, startPoint, endPoint )
  File "Report Area in Square Units.py", line 25, in sliceIntersections
    return measurementTool.calculateIntersectionsForLayer_startPoint_endPoint_( thisLayer, startPoint, endPoint )	
AttributeError: No attribute calculateIntersectionsForLayer_startPoint_endPoint_

**Comment by mekkablue** [comment]
should be fixed now
