### ISSUE TITLE
Steal sidebearings.py error

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#72]
```Start
Traceback (most recent call last):
  File "Steal sidebearings.py", line 168, in <module>
    MetricsCopy()
  File "Steal sidebearings.py", line 20, in __init__
    self.w.from_font = vanilla.PopUpButton( (150, 12, -15, 17), self.listOfMasterNames(), sizeStyle='small', callback=self.buttonCheck)
  File "Steal sidebearings.py", line 55, in listOfMasterNames
    myMasterNameList = [ "%s - %s" % ( m.font().familyName, m.name ) for m in self.listOfMasters ]
AttributeError: 'NoneType' object has no attribute 'familyName'
End
```

**Comment by mekkablue** [comment]
That means it could not determine all the currently opened font masters. The script runs fine for me.
