### ISSUE TITLE
Sync Components Across Masters

### ISSUE THREAD

**Issue by guidoferreyra** [mekkablue/Glyphs-Scripts#81]
Hi! Sync components across masters is not working here the console log.

Start
Processing DZ
Traceback (most recent call last):
  File "Sync Components Across Masters.py", line 60, in <module>
    process( thisLayer )
  File "Sync Components Across Masters.py", line 34, in process
    thisAnchor =  thisLayer.components[i].anchor()
TypeError: 'NoneType' object is not callable
End

Best regards!!

**Comment by mekkablue** [comment]
Fixed. Thx for reporting!
